#ifndef VOICE_RECOGNITION_VOICECODE_H_
#define VOICE_RECOGNITION_VOICECODE_H_
//move
struct voicecode{
	int code;
	int num;
};

#define VC_CODE_UNDEFINED -1
#define VC_CODE_FORWARD 2
#define VC_CODE_BACK 5
#define VC_CODE_RIGHT 8
#define VC_CODE_LEFT 11
#define VC_CODE_ROTATE 13
#define VC_CODE_STOP 14
//cannon
#define VC_CODE_CANNON_UP 15
#define VC_CODE_CANNON_DOWN 16
#define VC_CODE_CANNON_RIGHT 17
#define VC_CODE_CANNON_LEFT 18
//one word
#define VC_CODE_HOUTOU 12

#define VC_CODE_MODECHANGE 19
#define VC_CODE_UCHIKATA 20


#define VC_CODE_FIRE 21

#define VC_CODE_QUIZ 100
#define VC_CODE_CORRECT 101
#define VC_CODE_INCORRECT 102

#define VC_CODE_BLUE 103
#define VC_CODE_RED 104
#define VC_CODE_YELLOW 105
#define VC_CODE_GREEN 106
#define VC_CODE_WHITE 107
#define VC_CODE_BLACK 108

#define VC_CODE_EXIT 200

#endif  // VOICE_RECOGNITION_VOICECODE_H_
